version: '2'
services:
  graphing:
    build: .
    container_name: graphing
    privileged: true
    network_mode: "host"
    environment:
        - HOSTNAME=graphing
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
      - /proc:/host/proc:ro
